### PR TITLE
handle gallery emails

### PR DESCRIPTION
**Pull request by sei-tspencer**

### CODE REVIEW

**Review by sei-aschlackman — COMMENTED** [review]
It might be easier to have steamfitter look for a custom scope like `steamfitter-mail` and allow any clients with that scope.

**Comment by sei-tspencer** [comment]
> It might be easier to have steamfitter look for a custom scope like `steamfitter-mail` and allow any clients with that scope.

But then you would have to look at Identity to find all of the clients that can send email.  This seems to be more straight forward?  You just look at the steamfitter settings and you know which clients can send email.  Does that make sense?

**Comment by sei-aschlackman** [comment]
> > It might be easier to have steamfitter look for a custom scope like `steamfitter-mail` and allow any clients with that scope.
> 
> But then you would have to look at Identity to find all of the clients that can send email. This seems to be more straight forward? You just look at the steamfitter settings and you know which clients can send email. Does that make sense?

Either way works, but it seems to me to be what scopes are made for (I think?). Main practical difference would be you could add/remove access without back-end access to steamfitter (though that can be a pro or a con depending on your point of view). Being able to easily view what clients have what scopes sounds like a feature request for identity.

**Comment by sei-tspencer** [comment]
> > > It might be easier to have steamfitter look for a custom scope like `steamfitter-mail` and allow any clients with that scope.
> > 
> > 
> > But then you would have to look at Identity to find all of the clients that can send email. This seems to be more straight forward? You just look at the steamfitter settings and you know which clients can send email. Does that make sense?
> 
> Either way works, but it seems to me to be what scopes are made for (I think?). Main practical difference would be you could add/remove access without back-end access to steamfitter (though that can be a pro or a con depending on your point of view). Being able to easily view what clients have what scopes sounds like a feature request for identity.

I think it is a pro that you have to have access to the steamfitter back-end in order to enable another application's users to send email from steamfitter, especially without an existing "what clients have what scopes" feature.  It would certainly be easy to change over to using scopes in the future.

**Pull request closed without merging**
